listen_addr = "127.0.0.1:8008"

[db]
url = "postgres://postgres:root@127.0.0.1:5432/backend"

[jwt]
secret = "yoursecret"
expiry = 3600

[log]
file_name = "app.log"
rolling = "daily"
# added by Manish  (below), also prefer stf::fs there to load those in main
[tls]
cert = "certs/cert.pem"
key = "certs/key.pem"